spring:
  application:
     name: Library
  datasource:
     url: jdbc:mysql://localhost:3306/myschema
     username: root
     password: Dharani$123
  jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
     properties:
       hibernate:
         format_sql: true


springdoc:
  api-docs:
    path: /api-docs
